// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_VVA0rX7_9eIHAmCBNI-THku_c0aZANw',
    appId: '1:40042091076:web:f5ed82698e14a6067ee211',
    messagingSenderId: '40042091076',
    projectId: 'perfect-elearnn',
    authDomain: 'perfect-elearnn.firebaseapp.com',
    storageBucket: 'perfect-elearnn.firebasestorage.app',
    measurementId: 'G-TNHDSFD3S0',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASHDxlQtw-XAT1djFwFFalx7GJiuxlmog',
    appId: '1:40042091076:ios:1a43af6360e5e0827ee211',
    messagingSenderId: '40042091076',
    projectId: 'perfect-elearnn',
    storageBucket: 'perfect-elearnn.firebasestorage.app',
    androidClientId: '40042091076-nfe6nos8k5t53anc4qkdq485gr1t6ap2.apps.googleusercontent.com',
    iosClientId: '40042091076-i0miotvctm3ro71c67n5il2b6sjloevu.apps.googleusercontent.com',
    iosBundleId: 'com.example.perfectSuperAdmin',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHMd1DE5k0L1LOPgrNPWimtkT45pr3XkE',
    appId: '1:40042091076:android:c65a397fe24ef5ee7ee211',
    messagingSenderId: '40042091076',
    projectId: 'perfect-elearnn',
    storageBucket: 'perfect-elearnn.firebasestorage.app',
  );

}